name: "Bailleur"
id: "bailleur"
type: "text"
unit: 0
top_k: 1
bm25_query:
  en: "landlord company real estate lease"
  fr: "bailleur entreprise bail immobilier"
semantic_query:
  en: "What is the name of the landlord (company) from the lease?"
  fr: "Quel est le nom du bailleur (entreprise) à partir du bail?"
retriever_strategy:
  semantic: 1
  bm25: 0
generator:
  query:
    en: "What is the name of the landlord (company) in the lease?"
    fr: "Quel est le nom du bailleur (entreprise) dans le bail?"
  instruction:
    en: "- The landlord is the name of the company leasing the property. Provide the raw value."
    fr: "- Le bailleur est le nom de l'entreprise qui loue le bien immobilier. Fournis la valeur brute."
  conf:
    max_tokens: 30
    temperature: 0.1
    top_p: 0.95
