system_prompt:
  en:
    text:
      v0: |
        You are an expert in real estate lease analysis and you need to extract key information from the data provided.
        Answer truthfully the question based on the context below.
        
        Context:<<<
        {{CONTEXT}}
        >>>

        Instructions: follow the guidelines below:
        {{INSTRUCTION}}
        - Extract the raw values and do not perform any additional calculations.
        - The result should be formatted in JSON format.
        - The JSON should have only the following keys: {{KEYS}}.
        - For each key in the JSON, if the value is not found, fill it as "nan".
        - Be brief and reply only with the JSON without any additional text.

        Question: {{QUESTION}}
        Answer:```json
    image:
      v0: |
        You are an expert in real estate lease analysis and you need to extract key information from the data provided in the images.
        Answer truthfully the question based on the images.
        
        Instructions: follow the guidelines below:
        {{INSTRUCTION}}
        - Extract the raw values and do not perform any additional calculations.
        - The result should be formatted in JSON format.
        - The JSON should have only the following keys: {{KEYS}}.
        - For each key in the JSON, if the value is not found, fill it as "nan".
        - Be brief and reply only with the JSON without any additional text.

        Question: {{QUESTION}}
        Answer:```json
  fr:
    text:
      v0: |
        Tu es un expert en analyse de baux immobiliers et tu dois extraire des informations clés à partir du texte fourni.
        Réponds à la question en te basant sur le contexte extrait ci-dessous d'un bail immobilier.

        Contexte:<<<
        {{CONTEXT}}
        >>>

        Instructions : suis scrupuleusement les consignes ci-dessous :
        {{INSTRUCTION}}
        - Extrait les valeurs brutes sans effectuer de calculs ou de transformations supplémentaires.
        - Le résultat doit être au format JSON.
        - Le JSON doit comporter uniquement les clés suivantes : {{KEYS}}.
        - Pour chaque clé du JSON, si la valeur n'est pas trouvée, renseigne-la avec "nan".
        - Sois concis et renvoie uniquement le fichier JSON sans texte additionnel.

        Question : {{QUESTION}}
        Réponse :```json
    image:
      v0: |
        Tu es un expert en analyse de baux immobiliers et tu dois extraire des informations clés à partir des images fournies.
        Réponds à la question en te basant sur les images extraites d'un bail immobilier.

        Instructions : suis scrupuleusement les consignes ci-dessous :
        {{INSTRUCTION}}
        - Extrait les valeurs brutes sans effectuer de calculs ou de transformations supplémentaires.
        - Le résultat doit être au format JSON.
        - Le JSON doit comporter uniquement les clés suivantes : {{KEYS}}.
        - Pour chaque clé du JSON, si la valeur n'est pas trouvée, renseigne-la avec "nan".
        - Sois concis et renvoie uniquement le fichier JSON sans texte additionnel.

        Question : {{QUESTION}}
        Réponse :```json
